import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import type { Selection } from "../commands/select.js";
import { collectEnvVars } from "../secrets/interpolate.js";
import type { Catalog } from "./discover.js";
import type { ResolvedCatalog } from "./resolve.js";

// Copy the selected catalog artifacts from the (package) catalog into the
// target repo's .agents/ directory, so they are committed and provider symlinks
// resolve to repo-local paths (robust against npx cache clears / CI).
//
// Returns a ResolvedCatalog pointing at the repo-local .agents/ so callers can
// re-discover and write providers from the materialized source of truth.
export const materializeCatalog = (
  targetRoot: string,
  sourceCatalog: ResolvedCatalog,
  catalog: Catalog,
  selection: Selection,
): ResolvedCatalog => {
  const destRoot = resolve(targetRoot, ".agents");
  mkdirSync(destRoot, { recursive: true });

  // Skills: copy each selected skill dir, preserving its catalog-relative path
  // (e.g. skills/code/cleanup) so groups are retained.
  const keptSkillDirs: string[] = [];
  for (const skill of catalog.skills) {
    if (!selection.skills.includes(skill.name)) continue;
    const dest = resolve(destRoot, skill.sourcePath);
    mkdirSync(dirname(dest), { recursive: true });
    cpSync(skill.absDir, dest, { recursive: true, force: true });
    keptSkillDirs.push(skill.sourcePath);
  }

  // Commands: copy each selected command file.
  for (const command of catalog.commands) {
    if (!selection.commands.includes(command.name)) continue;
    const dest = resolve(destRoot, command.sourcePath);
    mkdirSync(dirname(dest), { recursive: true });
    cpSync(command.absPath, dest, { force: true });
  }

  // Filtered config.json: keep only selected MCP servers, plus shared/claude.
  const filteredConfig: Record<string, unknown> = {};
  if (catalog.config.shared) filteredConfig["shared"] = catalog.config.shared;
  const mcpServers: Record<string, unknown> = {};
  for (const mcp of catalog.mcp) {
    if (selection.mcp.includes(mcp.name)) mcpServers[mcp.name] = mcp.server;
  }
  if (Object.keys(mcpServers).length) filteredConfig["mcpServers"] = mcpServers;
  if (catalog.config.claude) filteredConfig["claude"] = catalog.config.claude;
  writeFileSync(
    resolve(destRoot, "config.json"),
    JSON.stringify(filteredConfig, null, 2) + "\n",
  );

  // Static docs shipped by the catalog.
  for (const file of ["AGENTS.md", "README.md"]) {
    const src = resolve(sourceCatalog.root, file);
    if (existsSync(src)) {
      cpSync(src, resolve(destRoot, file), { force: true });
    }
  }

  // Secrets template: generated from the ${VAR} placeholders the *selected*
  // MCP servers actually reference. No secrets needed -> no file. Never
  // clobbers an existing one.
  const envVars = collectEnvVars(mcpServers);
  const exampleDest = resolve(targetRoot, ".env.local.example");
  if (envVars.length && !existsSync(exampleDest)) {
    writeFileSync(exampleDest, envExampleContent(envVars));
  }

  return { source: sourceCatalog.source, root: destRoot };
};

const envExampleContent = (vars: string[]): string =>
  [
    "# Secrets for the selected MCP servers (generated by quiver).",
    "# Copy to `.env.local` (gitignored), fill in the values, then re-run",
    "# `quiver-cli sync`. Never commit `.env.local`.",
    "",
    ...vars.map((v) => `${v}=`),
    "",
  ].join("\n");

// Remove a skill/command artifact from the materialized repo .agents/, cleaning
// up empty group folders. Used by `remove`.
export const removeArtifact = (
  targetRoot: string,
  sourcePath: string,
): void => {
  const path = resolve(targetRoot, ".agents", sourcePath);
  rmSync(path, { recursive: true, force: true });
};
