import { resolve } from "node:path";

import TOML from "@iarna/toml";

import type { McpServer } from "../catalog/discover.js";
import type { ProviderInputs, ProviderPlan } from "./claude.js";
import type { FileOutput } from "./fsops.js";

// Codex reads skills natively from .agents/skills and AGENTS.md natively, so no
// shims are emitted for those. Custom slash commands are not documented for
// Codex, so commands are intentionally skipped here. Only MCP servers (TOML)
// are generated into project-scoped .codex/config.toml.
const buildConfig = (
  servers: Record<string, McpServer>,
): Record<string, unknown> | null => {
  if (Object.keys(servers).length === 0) return null;

  const mcpServers: Record<string, unknown> = {};
  for (const [name, server] of Object.entries(servers)) {
    if (server.transport === "http") {
      // Split headers: static values go to http_headers; ${VAR} placeholders
      // map to env_http_headers (Codex reads the secret from the environment),
      // so secrets never land in the committed config.toml.
      const httpHeaders: Record<string, string> = {};
      const envHeaders: Record<string, string> = {};
      for (const [key, value] of Object.entries(server.headers ?? {})) {
        const single = value.match(/^\$\{([^}]+)\}$/);
        const embedded = value.match(/\$\{([^}]+)\}/);
        if (single) {
          envHeaders[key] = single[1]!;
        } else if (embedded) {
          // Header mixes literal + ${VAR}; Codex can't template inline, so map
          // the whole header to the referenced env var as the closest option.
          envHeaders[key] = embedded[1]!;
        } else {
          httpHeaders[key] = value;
        }
      }
      mcpServers[name] = {
        url: server.url,
        ...(Object.keys(httpHeaders).length ? { http_headers: httpHeaders } : {}),
        ...(Object.keys(envHeaders).length
          ? { env_http_headers: envHeaders }
          : {}),
      };
    } else {
      mcpServers[name] = {
        command: server.command,
        ...(server.args && server.args.length ? { args: server.args } : {}),
        ...(server.env ? { env: server.env } : {}),
      };
    }
  }

  return { mcp_servers: mcpServers };
};

export const planCodex = (inputs: ProviderInputs): ProviderPlan => {
  const { targetRoot, rawMcpServers } = inputs;
  const files: FileOutput[] = [];
  const removeFiles: string[] = [];

  const config = buildConfig(rawMcpServers);
  const path = resolve(targetRoot, ".codex/config.toml");
  if (config) {
    files.push({
      path,
      content:
        "# Generated by quiver. Source of truth: .agents/config.json\n" +
        TOML.stringify(config as TOML.JsonMap),
    });
  } else {
    removeFiles.push(path);
  }

  // No skill/command shims for Codex.
  return { files, removeFiles, symlinks: [], managedDirs: [] };
};
