import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

// Generated provider shims + local secrets are not committed. The source of
// truth (.agents/ and quiver.lock) IS committed.
const HEADER = "# Generated by quiver (source of truth: .agents/ + quiver.lock)";
const SECRETS_COMMENT = "# Local secrets for MCP env-var interpolation";

const SHIM_ENTRIES = [
  ".claude/",
  ".opencode/",
  ".codex/",
  ".mcp.json",
  "opencode.json",
  "AGENTS.md",
  "CLAUDE.md",
];
const SECRET_ENTRIES = [".env.local"];

// Append only the entries that are not already present (exact line match), so
// pre-existing user blocks never produce duplicates.
export const patchGitignore = (targetRoot: string): boolean => {
  const path = resolve(targetRoot, ".gitignore");
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  const lines = new Set(current.split("\n").map((l) => l.trim()));

  const missingShims = SHIM_ENTRIES.filter((e) => !lines.has(e));
  const missingSecrets = SECRET_ENTRIES.filter((e) => !lines.has(e));
  if (missingShims.length === 0 && missingSecrets.length === 0) return false;

  const block: string[] = [];
  if (missingShims.length) block.push(HEADER, ...missingShims);
  if (missingSecrets.length) block.push(SECRETS_COMMENT, ...missingSecrets);

  const prefix = current && !current.endsWith("\n") ? "\n" : "";
  writeFileSync(
    path,
    current + prefix + (current ? "\n" : "") + block.join("\n") + "\n",
  );
  return true;
};

// Source-of-truth paths that must be committed. If the repo's ignore rules
// exclude them (e.g. a leftover block from an older setup), warn the user -
// otherwise a fresh clone would miss the catalog and lockfile entirely.
export const ignoredSourcePaths = (targetRoot: string): string[] => {
  try {
    const out = execFileSync(
      "git",
      ["check-ignore", ".agents", "quiver.lock"],
      { cwd: targetRoot, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
    );
    return out.split("\n").map((l) => l.trim()).filter(Boolean);
  } catch {
    // Not a git repo, git missing, or nothing ignored (exit 1) - all fine.
    return [];
  }
};
